version: "3.9"

services:
  api01: &api
    image: meopedevts/go-francisco:1.0
    hostname: api01
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    deploy:
     resources:
       limits:
         cpus: "0.3"
         memory: "50MB"

  api02:
    <<: *api
    hostname: api02
    ports:
      - "8080:8080"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
     resources:
       limits:
         cpus: "0.2"
         memory: "25MB"

  db:
    image: postgres:15.5
    hostname: db
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 3s
      timeout: 5s
      retries: 10
    volumes:
      - ./migration.sql:/docker-entrypoint-initdb.d/migration.sql
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf
    environment:
      POSTGRES_DB: rinha-db
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha2024
    deploy:
     resources:
       limits:
         cpus: "0.7"
         memory: "425MB"

networks:
  default:
    driver: bridge
    name: rinha-2024
